### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by aniriand** [austen0/dnd_5e_spells#1]
The script seems to contain some sort of syntax error.  When trying to run the script (with the example spell list creation syntax) it shows the following error: 

![image](https://cloud.githubusercontent.com/assets/25055221/21846510/c193ada4-d7f7-11e6-9eb8-ceea15033bc9.png)

Am I doing something wrong or is there an error in the script?

**Comment by austen0** [comment]
The script is only compatible with Python 2 (looks like you're using 3). I'll make a note of this in the readme and add a check to the script.
